import {
  IconAlertTriangle,
  IconBubbleText,
  IconMailFilled,
  IconPencil,
  IconSend,
  IconStar,
} from "@tabler/icons-react";

export const InboxData = [
  {
    id: 27,
    name: "Grace Lewis",
    type: "Social",
    description: "Check out this new community event!",
    date: "2025-07-27",
  },
  {
    id: 26,
    name: "Alexander Lee",
    type: "Work",
    description: "Follow-up on last week’s design meeting.",
    date: "2025-07-26",
  },
  {
    id: 25,
    name: "Victoria Martin",
    type: "Friends",
    description: "Photos from our last hiking adventure.",
    date: "2025-07-25",
  },
  {
    id: 24,
    name: "Henry Jackson",
    type: "Primary",
    description: "Course registration assistance and guidance.",
    date: "2025-07-24",
  },
  {
    id: 23,
    name: "Scarlett Thomas",
    type: "Work",
    description: "Updated credentials for your project account.",
    date: "2025-07-23",
  },
  {
    id: 22,
    name: "William Anderson",
    type: "Social",
    description: "Your post received 200+ likes!",
    date: "2025-07-22",
  },
  {
    id: 21,
    name: "Evelyn Taylor",
    type: "Friends",
    description: "Let’s catch up over coffee this weekend.",
    date: "2025-07-21",
  },
  {
    id: 20,
    name: "Elijah Moore",
    type: "Work",
    description: "Team meeting rescheduled to next Thursday.",
    date: "2025-07-20",
  },
  {
    id: 19,
    name: "Harper White",
    type: "Primary",
    description: "Your exam schedule has been released.",
    date: "2025-07-19",
  },
  {
    id: 18,
    name: "Benjamin Thompson",
    type: "Work",
    description: "Quarterly financial report is now available.",
    date: "2025-07-18",
  },
  {
    id: 17,
    name: "Charlotte Perez",
    type: "Social",
    description: "Join us for a webinar on personal branding.",
    date: "2025-07-17",
  },
  {
    id: 16,
    name: "James Gonzalez",
    type: "Friends",
    description: "Shared a new playlist for your road trip.",
    date: "2025-07-16",
  },
  {
    id: 15,
    name: "Ava Lee",
    type: "Primary",
    description: "Registration confirmation for upcoming workshop.",
    date: "2025-07-15",
  },
  {
    id: 14,
    name: "Ethan Hernandez",
    type: "Work",
    description: "Feedback on your recent project submission.",
    date: "2025-07-14",
  },
  {
    id: 13,
    name: "Mia Rodriguez",
    type: "Social",
    description: "New follower request from your photography page.",
    date: "2025-07-13",
  },
  {
    id: 12,
    name: "Lucas Martinez",
    type: "Work",
    description: "Invoice for web development services attached.",
    date: "2025-07-12",
  },
  {
    id: 11,
    name: "Isabella Garcia",
    type: "Friends",
    description: "Birthday party photos from last weekend!",
    date: "2025-07-11",
  },
  {
    id: 10,
    name: "Mason Miller",
    type: "Primary",
    description: "Welcome kit details for new students.",
    date: "2025-07-10",
  },
  {
    id: 9,
    name: "Olivia Davis",
    type: "Work",
    description: "Updated presentation slides for Monday’s meeting.",
    date: "2025-07-09",
  },
  {
    id: 8,
    name: "Noah Williams",
    type: "Social",
    description: "Event invitation: Startup Networking Night.",
    date: "2025-07-08",
  },
  {
    id: 7,
    name: "Amelia Brown",
    type: "Friends",
    description: "Let’s plan a weekend hiking trip soon!",
    date: "2025-07-07",
  },
  {
    id: 6,
    name: "Liam Johnson",
    type: "Work",
    description: "Project deadline reminder for Q3 initiatives.",
    date: "2025-07-06",
  },
  {
    id: 5,
    name: "Sophia Carter",
    type: "Primary",
    description: "Monthly newsletter with the latest campus updates.",
    date: "2025-07-05",
  },
  {
    id: 4,
    name: "Clifford Morgan",
    type: "Social",
    description: "Enhance Your Brand Potential With Giant Advertising Blimps",
    date: "2025-07-04",
  },
  {
    id: 3,
    name: "Peter Lewis",
    type: "Friends",
    description: "Vacation Home Rental Success",
    date: "2025-07-03",
  },
  {
    id: 2,
    name: "Minerva Barnett",
    type: "Work",
    description: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "2025-07-02",
  },
  {
    id: 1,
    name: "Jullu Jalal",
    type: "Primary",
    description: "Our Bachelor of Commerce program is ACBSP-accredited.",
    date: "2025-07-01",
  },
];

export const slideMail = [
  {
    id: 1,
    title: "My Email",
    children: [
      {
        id: 11,
        title: "Inbox",
        count: InboxData?.length,
        icon: (className?: string) => <IconMailFilled className={className} />,
        link: "/inbox",
      },
      {
        id: 12,
        title: "Starred",
        count: 0,
        icon: (className?: string) => <IconStar className={className} />,
        link: "/inbox/star",
      },
      {
        id: 13,
        title: "Sent",
        count: "23,000",
        icon: (className?: string) => <IconSend className={className} />,
        link: "/inbox/sent",
      },
      {
        id: 14,
        title: "Draft",
        count: "03",
        icon: (className?: string) => <IconPencil className={className} />,
        link: "/inbox/draft",
      },
      {
        id: 14,
        title: "Span",
        count: "10",
        icon: (className?: string) => (
          <IconAlertTriangle className={className} />
        ),
        link: "/inbox/span",
      },
      {
        id: 15,
        title: "Important",
        count: "18",
        icon: (className?: string) => <IconBubbleText className={className} />,
        link: "/inbox/important",
      },
      {
        id: 16,
        title: "Bin",
        count: "11",
        icon: (className?: string) => <IconBubbleText className={className} />,
        link: "/inbox/bin",
      },
    ],
  },
  {
    id: 3,
    title: "Label",
    children: [],
  },
];
